# Generated by Django 5.0.5 on 2024-05-13 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
